"""Generate profile.yaml from a life-story.md using a local LLM.

Usage:
    python main.py init-profile --life-story ~/CV/life-story.md --output profile.yaml
"""

import logging
import re
import yaml
from pathlib import Path
from typing import Optional

from llm import generate_structured, check_ollama_available, recommend_model

logger = logging.getLogger(__name__)

PROFILE_SCHEMA = """
{
  "skills": ["list of technical skills, frameworks, tools — 20-50 items"],
  "titles": ["list of 5-15 desired job titles that match the person's background"],
  "keywords": ["list of 10-20 domain keywords to boost matching"],
  "name": "full name",
  "email": "email address",
  "location": "current city, country",
  "summary": "2-3 sentence professional summary",
  "preferred_locations": ["list of cities/countries the person wants to work in"],
  "search_queries": ["list of 5-10 job search strings to use on job boards"],
  "seniority_level": "intern|junior|mid|senior|staff (best match for the person)"
}
"""


def generate_profile_from_life_story(
    life_story_path: Path,
    output_path: Path,
    model: Optional[str] = None,
) -> bool:
    """Read life-story.md and generate profile.yaml using a local LLM.

    Returns True on success, False on failure.
    """
    if not check_ollama_available():
        logger.error(
            "Ollama is not running. Start it with: ollama serve\n"
            "Then install a model: ollama pull qwen2.5:3b"
        )
        return False

    if not life_story_path.exists():
        logger.error("Life story file not found: %s", life_story_path)
        return False

    life_story = life_story_path.read_text(encoding="utf-8")
    if not model:
        model = recommend_model()

    logger.info("Generating profile.yaml from %s using %s ...", life_story_path, model)

    prompt = f"""Read this person's professional background and extract a structured profile.

LIFE STORY:
{life_story[:8000]}

Return a JSON object matching this schema:
{PROFILE_SCHEMA}

RULES:
- skills: include ALL programming languages, frameworks, tools, and domain skills mentioned
- titles: infer the roles this person would realistically apply for
- keywords: domain-specific terms that would boost relevance matching for their target jobs
- preferred_locations: extract from the life story or notes; include country and city names
- search_queries: concrete search strings to use on job boards (e.g. "computer vision engineer", "ML researcher robotics")
- seniority_level: based on years of experience and roles held

Return ONLY valid JSON. No explanation, no markdown."""

    data = generate_structured(prompt, model=model, max_tokens=3000)
    if not data:
        logger.error("LLM returned empty or invalid response")
        return False

    # Build profile.yaml structure
    profile = _build_profile_yaml(data)

    output_path.write_text(yaml.dump(profile, default_flow_style=False, allow_unicode=True, sort_keys=False), encoding="utf-8")
    logger.info("Profile written to %s", output_path)
    print(f"\nProfile generated: {output_path}")
    print("Review and edit it before running the pipeline.\n")
    _print_summary(data)
    return True


def _build_profile_yaml(data: dict) -> dict:
    """Convert LLM output into the full profile.yaml structure."""
    name = data.get("name", "YOUR NAME")
    email = data.get("email", "you@example.com")
    preferred_locations = data.get("preferred_locations", ["Remote"])

    # Build default search locations from preferred locations (country level)
    countries = [loc for loc in preferred_locations if len(loc.split(",")) == 1]
    if not countries:
        countries = preferred_locations[:5]

    return {
        "# Generated by profile_generator.py — review and edit before use": None,

        "skills": data.get("skills", []),
        "titles": data.get("titles", []),
        "keywords": data.get("keywords", []),

        "search": {
            "queries": data.get("search_queries", ["machine learning engineer"]),
            "locations": countries,
            "remote": True,
            "job_type": "",
            "max_age_days": 14,
            "boards": [
                "indeed", "glassdoor", "google", "linkedin",
                "arbeitnow", "himalayas", "themuse",
                "greenhouse", "lever",
                "linkedin_posts", "internet",
            ],
        },

        "companies": {
            "greenhouse": [],
            "lever": [],
        },

        "preferred_locations": preferred_locations,
        "remote_preferred": True,

        "weights": {
            "title": 0.10,
            "skills": 0.30,
            "semantic": 0.35,
            "location": 0.10,
            "experience": 0.02,
            "seniority": 0.10,
            "specialty": 0.03,
            "recency": 0.0,
        },

        "pipeline": {
            "auto_apply_threshold": 0.50,
            "max_applications_per_run": 10,
            "email_recipient": email,
            "email_digest_interval_days": 2,
            "cv_dir": "./cv",
            "ollama_model": "qwen3.5:9b",
        },
    }


def _print_summary(data: dict) -> None:
    print(f"Name:      {data.get('name', '?')}")
    print(f"Email:     {data.get('email', '?')}")
    print(f"Seniority: {data.get('seniority_level', '?')}")
    print(f"Skills:    {len(data.get('skills', []))} extracted")
    print(f"Titles:    {', '.join(data.get('titles', [])[:4])} ...")
    print(f"Locations: {', '.join(data.get('preferred_locations', [])[:4])}")
